### ISSUE TITLE
Usage error

### ISSUE THREAD

**Issue by pjduplooy2022** [WhereGroup/mapqonverter#26]
Hi guys.

I am trying to convert an ArcMap project to a QGIS project.

On running the toolbox, I get the following error:

Executing: Mapqonverter C:\QGIS\test.qgz
Start Time: Sun Apr 17 22:51:43 2022
Running script Mapqonverter...
Failed script Mapqonverter...

Traceback (most recent call last):
  File "C:\mapqonverter\mapqonverter.py", line 14, in <module>
    from map.metadata import Metadata
  File "C:\mapqonverter\map\metadata.py", line 1, in <module>
    from modules.arcGisModules import ArcGisModules
  File "C:\mapqonverter\modules\arcGisModules.py", line 5, in <module>
    class ArcGisModules:
  File "C:\mapqonverter\modules\arcGisModules.py", line 15, in ArcGisModules
    module_framework = GetModule("{lib_path}esriFramework.olb".format(lib_path=lib_path))
  File "C:\Python27\ArcGIS10.8\lib\site-packages\comtypes\client\_generate.py", line 159, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Python27\ArcGIS10.8\lib\site-packages\comtypes\client\_generate.py", line 242, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Python27\ArcGIS10.8\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Python27\ArcGIS10.8\lib\site-packages\comtypes\gen\_866AE5D3_530C_11D2_A2BD_0000F8774FB5_0_10_8.py", line 350, in <module>
    AppROT._com_interfaces_ = [IAppROT, comtypes.gen._59FCCD31_434C_4017_BDEF_DB4B7EDC9CE0_0_10_8.IConnectionPointContainer]
AttributeError: 'module' object has no attribute 'IConnectionPointContainer'

Failed to execute (Mapqonverter).
Failed at Sun Apr 17 22:51:44 2022 (Elapsed Time: 0.95 seconds)

I am using ArcMap 10.8.1 and QGIS nightly (On Windows).

Python for this version of ArcMap is 2.17.18, and it fails using the 32 bit version.  Also fails with 64 bit version.  Background Geoprocessing is installed and ArcMap is set to use it.

Comtypes is version 1.1.11.

I am attaching both the shpfile (in a zip archive), as well as the mxd.

I hope you can help me.

Pieter
[data.zip](https://github.com/WhereGroup/mapqonverter/files/8502435/data.zip)
[test.zip](https://github.com/WhereGroup/mapqonverter/files/8502438/test.zip)

**Comment by pheidelb** [comment]
Hi Pieter,

sorry for the delay. I think the comtypes version is wrong. For me comtypes Version 1.1.7 is working well with Python 2.7.18. and ArcMap 10.8.1.

When you change the comtypes version, you should execute the script clear_comtypes_cache.py in "C:\Python27\ArcGIS10.8\Scripts" 

Hope this helps!

Peter

**Comment by gmaFFFFF** [comment]
> Hi Pieter,
> 
> sorry for the delay. I think the comtypes version is wrong. For me comtypes Version 1.1.7 is working well with Python 2.7.18. and ArcMap 10.8.1.
> 
> When you change the comtypes version, you should execute the script clear_comtypes_cache.py in "C:\Python27\ArcGIS10.8\Scripts"
> 
> Hope this helps!
> 
> Peter

work for me

**Comment by pheidelb** [comment]
Correct version is now written in readme.
